id: A4B521999
title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:24:43.008704
  last_modified_at: 2022-03-01 02:24:43.008711
