id: A4B521999
title: Prayer to Smṛtijñānakīrti
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:24:43.010373
  last_modified_at: 2022-03-01 02:24:43.010377
